name: Build My React App
on:
  push:
    branches: [ master ]

jobs:
  build-react-app:
    runs-on : ubuntu-latest

    steps:
      - uses: actions/checkout@v6.0.2
      - name: Setup Node JS
        uses: actions/setup-node@v6.4.0
        with:
          node-version: 26.x
      - name: Install Dependencies
        run: npm install
      - name: Build React App
        run: npm run build
    
      
    
