name: Build My React App

on:
  push:
    branches:
      - master

jobs:
  build-react-app:
    runs-on: ubuntu-latest

    env:
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    defaults:
      run:
        working-directory: first

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: npm
          cache-dependency-path: first/package-lock.json

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build
